<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>$(AssemblyBaseName)</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
    <AzureCosmosDisableNewtonsoftJsonCheck>True</AzureCosmosDisableNewtonsoftJsonCheck>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <PackageId>FSharp.Collections.Immutable</PackageId>
    <Title>FSharp.Collections.Immutable</Title>
    <Summary>F# API for using Microsoft Azure Cosmos DB service via NoSQL API</Summary>
    <Description>Provides extension methods for the FeedIterator and computation expressions to build operations</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ImmutableCollectionUtil.fs" />
    <Compile Include="FlatList.fsi" />
    <Compile Include="FlatList.fs" />
    <Compile Include="Stack.fsi" />
    <Compile Include="Stack.fs" />
    <Compile Include="ImmutableList.fsi" />
    <Compile Include="ImmutableList.fs" />
    <Compile Include="IndexedList.fsi" />
    <Compile Include="IndexedList.fs" />
    <Compile Include="Queue.fsi" />
    <Compile Include="Queue.fs" />
    <Compile Include="IndexedSeq.fsi" />
    <Compile Include="IndexedSeq.fs" />
    <Compile Include="Maps.fsi" />
    <Compile Include="Maps.fs" />
    <Compile Include="Sets.fsi" />
    <Compile Include="Sets.fs" />
    <Compile Include="Seq.fsi" />
    <Compile Include="Seq.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
