<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>$(AssemblyBaseName).Tests</AssemblyName>

    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="testconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="TestCategories.fs" />
    <Compile Include="FlatList.fs" />
    <Compile Include="Stack.fs" />
    <Compile Include="ImmutableList.fs" />
    <Compile Include="Queue.fs" />
    <Compile Include="IndexedSeq.fs" />
    <Compile Include="Maps.fs" />
    <Compile Include="Sets.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Unquote" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FSharp.Collections.Immutable\FSharp.Collections.Immutable.fsproj" />
  </ItemGroup>

</Project>
